=== mohamedYoussfi/xml-svg-master-iibdcc/meteo.dtd
<!ELEMENT meteo (mesure+) >
<!ELEMENT mesure (ville+) >
<!ELEMENT ville EMPTY >
<!ATTLIST mesure
                date CDATA #REQUIRED>
<!ATTLIST ville 
                nom CDATA #REQUIRED
                temperature CDATA #REQUIRED>

=== mohamedYoussfi/xml-svg-master-iibdcc/Sans_titre10.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE meteo SYSTEM "file:/Users/mohamedyoussfi/Documents/svg/meteo.dtd">
<meteo>
    <mesure date="2011-11-11">
        <ville nom="Casa" temperature="45"/>
        <ville nom="" temperature="rytrt"/>
        <ville nom="" temperature=""/>
        <ville nom="" temperature=""/>
    </mesure>
    <mesure date="">
        <ville nom="" temperature=""/>
        <ville nom="" temperature=""/>
        <ville nom="" temperature=""/>
    </mesure>
</meteo>
